[package]
name = "smoo-gadget-core"
version = { workspace = true }
edition = "2024"
rust-version = "1.87"
license = "GPL-3.0-only"

[features]
default = []
apkbuild = ["smoo-gadget-ublk/apkbuild"]

[dependencies]
anyhow = "1.0.100"
bitflags = { version = "2.6.0", features = ["serde"] }
dma-heap = "0.4.1"
libc = "0.2.177"
mmap = "0.1.1"
nix = { version = "0.30.1", features = ["ioctl", "poll"] }
rand = "0.8.5"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
smoo-proto = { path = "../smoo-proto" }
smoo-gadget-ublk = { path = "../smoo-gadget-ublk" }
tokio = { version = "1.48.0", features = ["fs", "io-util", "rt"] }
tracing = "0.1.41"
async-trait = "0.1.83"

[dev-dependencies]
tempfile = "3.14.0"
