[package]
name = "smoo-gadget-core"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
anyhow = "1.0.100"
dma-heap = "0.4.1"
libc = "0.2.177"
mmap = "0.1.1"
nix = { version = "0.30.1", features = ["ioctl", "poll"] }
smoo-proto = { path = "../smoo-proto" }
tokio = { version = "1.48.0", features = ["fs", "io-util", "rt"] }
tracing = "0.1.41"
