[package]
name = "smoo-gadget-buffers"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dma-heap = "0.4.1"
libc = "0.2.153"
mmap = "0.1.1"
nix = { version = "0.30.1", features = ["ioctl"] }
tracing = "0.1.41"
