[package]
name = "smoo-host-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.83"
tokio = { version = "1.48.0", features = ["fs", "io-util", "rt", "macros", "sync"] }
tracing = "0.1.41"
smoo-proto = { path = "../smoo-proto" }
