[package]
name = "smoo-host-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
clap = { version = "4.5.20", features = ["derive"] }
rusb = "0.9.4"
smoo-host-blocksources = { path = "../../crates/smoo-host-blocksources" }
smoo-host-core = { path = "../../crates/smoo-host-core" }
smoo-host-rusb = { path = "../../crates/smoo-host-rusb" }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
