[package]
name = "smoo-host-cli"
version = { workspace = true }
edition = "2021"
rust-version = "1.87"
license = "GPL-3.0-only"

[dependencies]
anyhow = "1.0.100"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "signal", "time"] }
smoo-host-app = { path = "../../crates/smoo-host-app" }
