[package]
name = "smoo-host-blocksources"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
smoo-host-core = { path = "../smoo-host-core", features = ["std"] }
tokio = { version = "1.48.0", features = ["fs", "io-util", "sync"] }
tracing = "0.1.41"
