[package]
name = "smoo-proto"
version = { workspace = true }
edition = "2024"
rust-version = { workspace = true }
license = "MIT"
repository = { workspace = true }
description = { workspace = true }

[dependencies]
heapless = { version = "0.8.0", default-features = false, features = ["serde"] }
