[package]
name = "smoo-proto"
version = { workspace = true }
edition = "2024"
rust-version = "1.87"
license = "MIT"

[dependencies]
heapless = { version = "0.8.0", default-features = false, features = ["serde"] }
